# SubNav
menu:
  #å…³äºæˆ‘: /2014/aboutme/
  å‹é“¾: /2014/friends/
  å…³äºæˆ‘: haha
subnav:
  github: "https://github.com/YonSunZhen"
  weibo: "http://weibo.com/u/5263249441"
  #zhihu: "https://www.zhihu.com/people/hu-yang-11-57/"
  email: "mailto:hufy78@gmail.com"
  sf: "https://segmentfault.com/u/youthink"
  #youthol: "http://www.youthol.cn"
  rss: "/atom.xml"

description: å¤©é©¬è¡Œç©ºï¼Œçˆ±ç”Ÿæ´»ï¼Œçˆ±coding

# SEO
seo_keywords: hexo,ä¸ªäººåšå®¢,blog
seo_description: æŸæŸçš„ä¸ªäººåšå®¢

favicon: /favicon.ico

#ä½ çš„å¤´åƒurl
avatar: https://tva3.sinaimg.cn/crop.0.0.200.200.180/005Kc3C1jw8f2uep0hhkvj305k05k3yk.jpg

# é¦–é¡µå·¦ä¾§è¾¹æ èƒŒæ™¯å›¾ç‰‡(åœ¨æœ¬åœ°çš„)
# å¯é…ç½®å¤šä¸ªéšæœºæŒ‘é€‰ä¸€å¼ 
leftBackground:
  - https://yonsunzhen.github.io/img/left-1.jpg
  - https://yonsunzhen.github.io/img/left-2.jpg
  - https://yonsunzhen.github.io/img/left-3.jpg
  - https://yonsunzhen.github.io/img/left-4.jpg
  - https://yonsunzhen.github.io/img/left-5.jpg
  - https://yonsunzhen.github.io/img/left-6.jpg
  - https://yonsunzhen.github.io/img/left-7.jpg

# å±•ç¤ºæ›´æ–°æ—¶é—´
display_updated: true

# æ–‡ç« é¡µçš„å…³äºè½¬è½½é“¾æ¥
copyright_url: https://888.com/index.html

# åº•éƒ¨çš„å¤‡æ¡ˆä¿¡æ¯ç­‰
copyright_date: 2013-2019
beian_info: æŸæŸçš„åšå®¢ äº¬ICPå¤‡xxxxxxå·

# Online contact
daovoice: true
daovoice_app_id: 123456 #è¾“å…¥app_id

# Data statistics
baidu_analytics: true
baidu_analytics_code: 1b5ca8bbd5cf95a2263942c7c20476d9

#Comments
# https://github.com/gitalk/gitalk
gitalk: true
gitalk_clientID: 4008c278909d8497d8ad
gitalk_clientSecret: e27df4736052523348bbf856ba03e1d350143b93
gitalk_repo: YonSunZhen.github.io
gitalk_owner: YonSunZhen
gitalk_admin: YonSunZhen
# æ˜¯å¦å¯ç”¨è¯„è®ºæ¡†çš„å…¨å±é®ç½©æ•ˆæœ
gitalk_distractionFreeMode: false

#consoleå½©è›‹
console: true
console_color: '#6190e8'
console_config:
  - '\næ¬¢è¿è®¿é—® https://hufangyun.com ï¼Œå›´è§‚æˆ‘çš„åšå®¢(ã¥ï½¡â—•â€¿â€¿â—•ï½¡)ã¥ï¼\n'
  - '\næœ¬åšå®¢ä½¿ç”¨ %cHexo%c æ­å»ºï¼Œåšå®¢ä¸»é¢˜ä¸ºæœ¬äººå¼€å‘çš„ %chexo-themes-yearn%c ~~~ ğŸ‰ğŸ‰ğŸ‰ \n\næºç  https://github.com/Youthink/hexo-themes-yearn \n\nå¦‚æœå–œæ¬¢å¯ä»¥ star æ”¯æŒä¸€ä¸‹ â¤ï¸~\n'
  - '\næ‰«æä¸‹é¢çš„äºŒç»´ç ï¼Œåœ¨æ‰‹æœºä¸ŠæŸ¥çœ‹åšå®¢ï¼\n'
  - 'https://static.hufangyun.com/blog-url-qrcode-180-180.png'
  - '\n æƒ³çŸ¥é“è¿™ä¸ªæ•ˆæœå¦‚ä½•å®ç°çš„ï¼Ÿåšå®¢å†…æœç´¢ console å½©è›‹ ğŸš€ ï¼\n'


# é•¿æ—¶é—´æœªæ›´æ–°çš„åšæ–‡æ˜¾ç¤ºæé†’
overdue_auto_all: false
overdue_remind: æœ¬æ–‡æœ€åæ›´æ–°äº$dayå¤©å‰ï¼Œæ–‡ä¸­æ‰€æè¿°çš„ä¿¡æ¯å¯èƒ½å·²å‘ç”Ÿæ”¹å˜ã€‚

# search hexo-generator-json-content
jsonContent:
  meta: false
  pages: false
  posts:
    title: true
    date: true
    path: true
    text: false
    raw: false
    content: false
    slug: false
    updated: false
    comments: false
    link: false
    permalink: false
    excerpt: false
    categories: false
    tags: false

